services:
  - type: web
    name: kyotika-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false # Set the contents of config/master.key on Blueprint creation
      - key: WEB_CONCURRENCY
        value: 2 # Recommended default for small instances
